#!/usr/bin/env python3
"""Fetch KR/JP Pokemon names from PokeAPI and emit a TS module.

Output: src/lib/pokemonNamesKoJa.ts — exports POKEMON_KO_TO_JA: Record<string,string>.

Run with: python3 scripts/fetch-pokemon-names.py
"""
from __future__ import annotations

import json
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from urllib.request import Request, urlopen
from urllib.error import URLError

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "lib" / "pokemonNamesKoJa.ts"
# 모바일도 같은 사전을 사용 — 동일 내용을 함께 출력해 두 앱을 동기화한다.
OUT_MOBILE = ROOT / "mobile" / "src" / "lib" / "pokemonNamesKoJa.ts"
TOTAL = 1025
CONCURRENCY = 6
RETRIES = 4
UA = "Mozilla/5.0 (compatible; arvotcg-build/1.0; +https://www.poke-30.com)"

def fetch(species_id: int) -> tuple[int, str | None, str | None]:
    url = f"https://pokeapi.co/api/v2/pokemon-species/{species_id}/"
    for attempt in range(RETRIES):
        try:
            req = Request(url, headers={"Accept": "application/json", "User-Agent": UA})
            with urlopen(req, timeout=20) as r:
                data = json.loads(r.read().decode())
            ko = ja = None
            for n in data.get("names", []):
                lang = n.get("language", {}).get("name")
                name = n.get("name")
                if lang == "ko" and name:
                    ko = name
                elif lang == "ja-hrkt" and name and not ja:
                    ja = name
                elif lang == "ja" and name and not ja:
                    ja = name
            return species_id, ko, ja
        except (URLError, json.JSONDecodeError, TimeoutError) as e:
            if attempt == RETRIES - 1:
                print(f"!! {species_id} failed: {e}", file=sys.stderr)
                return species_id, None, None
            time.sleep(0.5 * (attempt + 1))
    return species_id, None, None

def main() -> None:
    rows: list[tuple[int, str, str]] = []
    misses: list[int] = []
    print(f">> fetching {TOTAL} species with concurrency={CONCURRENCY}")
    started = time.time()
    with ThreadPoolExecutor(max_workers=CONCURRENCY) as ex:
        futures = {ex.submit(fetch, i): i for i in range(1, TOTAL + 1)}
        done = 0
        for fut in as_completed(futures):
            sid, ko, ja = fut.result()
            done += 1
            if done % 100 == 0:
                print(f"   {done}/{TOTAL}")
            if ko and ja:
                rows.append((sid, ko, ja))
            else:
                misses.append(sid)
    rows.sort(key=lambda r: r[0])
    print(f">> done in {time.time() - started:.1f}s. {len(rows)} mapped, {len(misses)} missing")
    if misses:
        print(f"   missing ids: {misses[:30]}{' ...' if len(misses) > 30 else ''}", file=sys.stderr)

    lines = [
        "// AUTO-GENERATED by scripts/fetch-pokemon-names.py — DO NOT EDIT BY HAND.",
        "// Source: PokeAPI (https://pokeapi.co) species 1..1025, KO + JA(katakana).",
        "// Re-run the script to refresh when new species ship.",
        "",
        "/** Korean Pokemon name -> Japanese (katakana) name. */",
        "export const POKEMON_KO_TO_JA: Record<string, string> = {",
    ]
    seen = set()
    for sid, ko, ja in rows:
        if ko in seen:
            continue
        seen.add(ko)
        ko_lit = json.dumps(ko, ensure_ascii=False)
        ja_lit = json.dumps(ja, ensure_ascii=False)
        lines.append(f"  {ko_lit}: {ja_lit}, // #{sid}")
    lines.append("};")
    lines.append("")
    text = "\n".join(lines)
    for path in (OUT, OUT_MOBILE):
        path.write_text(text, encoding="utf-8")
        print(f">> wrote {path.relative_to(Path.cwd())} ({len(seen)} entries)")

if __name__ == "__main__":
    main()
